### ISSUE TITLE
YYYY-MM-DD	example

### ISSUE THREAD

**Issue by kaihendry** [datagovsg/data-quality#1]
`42035` doesn't make a lot of sense.

Sidenote: You might want to defer to WHATWG definition of time since ISO8601 is too complex. IIUC it's a sane subset & of course it maps to browser implementations.

https://html.spec.whatwg.org/multipage/infrastructure.html#dates-and-times

**Comment by linzhaowei** [comment]
Thanks Kai, have fixed the typo!
